### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'clamp'

### ISSUE THREAD

**Issue by Cresynia** [CEA-LIST/MonoProb#1]
Thanks for your great work! I met a problem when I run it, and want to ask how to solve it.
In trainer.py:
 
depth_samples, probas = self.offsets_sampling(depth, uncert).clamp(min=1e-3, max=None)
      
AttributeError: 'tuple' object has no attribute 'clamp'

Thanks!

**Comment by marsalr** [comment]
Thanks for the bug report, it is fixed!

**Comment by Cresynia** [comment]
Got it! Thanks!
