### ISSUE TITLE
what's the teacher's checkpoints

### ISSUE THREAD

**Issue by Cresynia** [CEA-LIST/MonoProb#2]
Here when I run it with self-distillation, where can I find teacher's checkpoints.
Thanks!
load_weights_folder /path/of/the/teacher's/checkpoints

**Comment by marsalr** [comment]
Use the checkpoints that have not been trained with self-distillation as teacher's checkpoints. 
For instance, `M_640x192_resnet18_monoprob_self` has been trained with `M_640x192_resnet18_monoprob` as teacher's checkpoints.

**Comment by Cresynia** [comment]
Thanks!
