### ISSUE TITLE
Problem with self-distillation: KeyError

### ISSUE THREAD

**Issue by Cresynia** [CEA-LIST/MonoProb#3]
Thanks for your help!
When I run MonoProb M with self-distillation, I met the problem:

model_dict = self.teacher_models[n].state_dict()
                 ~~~~~~~~~~~~~~~~~~~^^^
KeyError: 'pose_encoder'.

**Comment by marsalr** [comment]
You're welcome!
Maybe it is because `teacher_models` only contains the keys `encoder` and `depth`. So try adding `--models_to_load encoder depth` to the command to train MonoProb with self-distillation. Let me know if it works.

**Comment by Cresynia** [comment]
Thanks so much! I can run it! And before that, I met another problem about the self.loss_fn = SelfLoss(stud_dist=self.opt.dist_self, 
shouldn't I set --dist_self normal in the command?

**Comment by marsalr** [comment]
Glad it works!
Yes you can do that, I have set `dist_self='normal'` as default in the `options.py` file. Thanks!
